import { NextRequest, NextResponse } from "next/server";
import { GoogleGenAI } from "@google/genai";

export async function POST(req: NextRequest) {
  try {
    const body = await req.json();
    const userMessage = body.message;

    if (!userMessage || typeof userMessage !== "string") {
      return NextResponse.json(
        { error: "Message is missing or it's invalid" },
        { status: 400 }
      );
    }

    const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY });

    const response = await ai.models.generateContent({
      model: "gemini-2.0-flash",
      contents: userMessage,
    });

    if (!response.text) {
      return NextResponse.json(
        { error: "No message generated by the AI model" },
        { status: 500 }
      );
    }

    return NextResponse.json({ text: response.text });
  } catch (error) {
    console.log("AI model error:", error);
    return NextResponse.json(
      { error: "AI model internal error" },
      { status: 500 }
    );
  }
}
